### ISSUE TITLE
Un-selecting Star Partially not Working

### ISSUE THREAD

**Issue by nhdmalik** [timheuer/callisto#144]
Hi
If e.g. we have Value = 2.6 then it shows 2.6 star with foreground color and if select reaming part of third star it fill it with foreground color and Value become 3. But it cannot reverse Value from 3 to 2.6. means star cannot un-selected partially.
Thanks

**Comment by timheuer** [comment]
By design.  The star selection is "user rating" -- there are no partial
"user rating" options by design.  The Value is meant to represent your
aggregate value of the rating, not an individual.  Consider Yelp as an
example.  I can't give a location 3.5 stars...I have to choose either 3 or
4 stars.  However the location can have an aggregate rating of 3.5 because
of all ratings supplied.

This is the same model and by design.

**Comment by nhdmalik** [comment]
thanks timheuer.
