### ISSUE TITLE
SetttingsFlyout being blocked by Onscreen Keyboard

### ISSUE THREAD

**Issue by KevinAnthony** [timheuer/callisto#195]
If you have TextBox's in your SettingsFlyout, and you click on one of them, it can become hidden by the onscreen keyboard.

**Comment by timheuer** [comment]
@kevinanthiny what build are you using here?  The sample app has this and does not repro

**Comment by KevinAnthony** [comment]
@timheuer 1.2.7
Here is a Video of the problem
https://www.dropbox.com/s/yn5v7ohxqdsvoq7/IMG_0596.MOV

**Comment by timheuer** [comment]
Got it, thanks for the visual.  This is actually by design.  The IHM (on screen keyboard) scrolls into view to the text input area.  You happen to have another text input area underneath.  The user could either pan (if you have scrollable content) to get to that or use Tab (on the software keyboard).

It isn't a great design of the IHM interaction, I'll agree, but that is how the interaction works with the software keyboard.  The control here is doing the correct thing and ensuring that we scroll into view the currently focused input selected.
