### ISSUE TITLE
Rating item colour when white background

### ISSUE THREAD

**Issue by cjgaliana** [timheuer/callisto#197]
Hi,
In a white background app, when you add the rating control the non-selected starts are transparent instead of grey

For example, this is the code to add the rating control that I have

< callisto:Rating ReadOnlyFill="#FFF1E702" IsEnabled="False"/>

It is possible change the default grey for non-selected items?

**Comment by timheuer** [comment]
How do you have the white background app?  Are you using RequestedTheme="Light" in your app.xaml or have you set it in your app grid somewhere?  I suspect the latter and you are picking up the dark-theme definitions of the control (which in this case would be a 'white' non-selected color).  I'd recommend using RequestedTheme="Light" in your app.xaml if you have a truly light-themed app.

Otherwise you'd have to overwrite RatingItemBackgroundThemeBrush definition in app.xaml.  Using the RequestedTheme is the recommended approach here.
