### ISSUE TITLE
Flyout positioning screws up if opening repeatedly quickly

### ISSUE THREAD

**Issue by longzheng** [timheuer/callisto#26]
If you keep invoking the flyout really quickly, the flyout still sometimes appear at the non-desired position.
1. Set flyout to open from top
2. Repeatedly click button quickly
3. Flyout will open on right

**Comment by daniel-chambers** [comment]
I also have a layout issue with the Flyout; it happens randomly when opening the flyout. I don't know whether the cause is the same as Long's problem (however it wouldn't surprise me, hence posting in this issue), but I managed to trace the problem to how the control measures its own size.

In PerformPlacement, when the CalculateHorizontalOffset and CalculateVerticalCenterOffset methods are called, ActualWidth and ActualHeight are read, and these (seemingly) randomly come back as 0 sometimes. When they do, the layout screws up. 

For me, I'm trying to display a flyout to the right of a button, and so the popup randomly appears aligned half way down the button if ActualHeight returns 0 instead of the real value.

**Comment by daniel-chambers** [comment]
I have tested this on Windows 8 Release Preview with Callisto v1.0.1 and this behaviour, although less frequent, still occurs. :(

**Comment by daniel-chambers** [comment]
Here's a repro application: http://sdrv.ms/K8w4Xj

**Comment by timheuer** [comment]
This seems to have to do with what is in the current visual tree...

**Comment by John-Garland** [comment]
Tim - I have been reproducing this and tracking it down.  It appears that it is a problem in flyout.cs --> in OnHostPopupOpened, sometimes the popup is "opened" - the event is received, even though the _hostPopup has an ActualHeight and ActualWidth of 0.0.  As you can imagine, this screws messes up the offsets for all future calculations.

What seems to be working for me is to duplicate the OnHostPopupOpened content in a handler for _hostPopup.SizeChanged -- it is a bit heavy-handed, but it catches the condition where the ActtualWidth/ActualHeight are updated after the initial "bad" 0.0 values and triggers repositioning based on good values.

There's probably more finesse that can be exercised in an eventual solution (if this is in fact the right path to take), but figured I'd share this to at least suggest one possible resolution.  I could probably submit this as a contribution myself, but I'm not comfortable with my familiarity with Git at this point.

**Comment by timheuer** [comment]
unfortunately this causes a flicker in some instances.  I'll see if I can
catch the 0 measure and force measure again.

---

http://timheuer.com/blog/
twitter: @timheuer

On Tue, Jun 26, 2012 at 2:52 PM, avidgator <
reply@reply.github.com

**Comment by John-Garland** [comment]
Not sure if it is the same flicker I saw - and we are certainly entering kludge territory here (if we're not already there) - I overcame one flicker scenario by setting up for either-or behavior.  In OnHostPopupOpened, if the Actual values are zero, set a flag and exit before going through the rest of the function.  In the SizeChanged handler, only go through the presentation logic from PopupOpened if that flag was set (and reset the flag.)  UGLY, and hopefully just a short-term fix until the original Open vs Sized dilemma can be resolved.

Hopefully the net gain here, however, is that we get on the right trick to find the correct solution to the problem...

**Comment by timheuer** [comment]
Heh, your kludge may be the solution :-).  What is happening is we're
opening the Popup off-screen in order to get some cords to position.  At
that moment the content may be empty thus the 0/0 size.  It's a race
condition for sure it seems like here where the Measure happens at the
moment where 0/0 exists.

-th

---

http://timheuer.com/blog/
twitter: @timheuer

On Wed, Jun 27, 2012 at 6:00 AM, avidgator <
reply@reply.github.com

**Comment by jvlppm** [comment]
Solution based on avidgator's tips:

@ Controls/Flyout/Flyout.cs:

```
     private void OnHostPopupOpened(object sender, object e)
     {
        if (_hostPopup.ActualHeight == 0 || _hostPopup.ActualWidth == 0)
        {
            SizeChangedEventHandler updatePosition = null;
            updatePosition = (s, eP) =>
                 {
                     if (eP.NewSize.Width != 0 && eP.NewSize.Height != 0)
                     {
                         OnHostPopupOpened(s, eP);
                         SizeChanged -= updatePosition;
                     }
                 };
            SizeChanged += updatePosition;
        }

         _hostPopup.HorizontalOffset = this.HorizontalOffset;
```

**Comment by John-Garland** [comment]
In my tests I didn't try it with an inline lambda, but yes, you captured most of what I was trying to communicate.  For some reason, it feels "less dirty" with the lambda than it did with a dedicated member variable.  A couple of notes:
- Should there be a "return;" statement following the "SizeChancge += updatePosition;" call?
- Not sure if the ActualHeight/ActualWidth check should be an "or" or an "and" - I was thinking "and."  Is there a case where it can re-enter the loop based on the SizeChanged handler with a set ActualHeight but a zero ActualWidth (or vice versa?)

**Comment by jvlppm** [comment]
it does not work with a return after "SizeChanged += updatePosition;", the flyout simply does not show (haven't checked why).
I think that the reposition of the flyout should occur always when the size is changed, because if it did change, it would not be in a correct position anymore (at least in the case of a Bottom placement), so that the event would be always signed.
haven't tried that yet, but this would change the current behavior when the flyout's content change in size.
