### ISSUE TITLE
Rename LiveTile

### ISSUE THREAD

**Issue by timheuer** [timheuer/callisto#4]
I wonder if we should rename LiveTile -- this is very much a Start Screen term and we don't want to confuse what the developer creates with something that won't show up on the Start Screen experience?

**Comment by dotMorten** [comment]
You mentioned HubTile, but after looking into what that does on the Windows Phone, it's actually quite different from what that does, and Win8 doesn't have a "hub" like WP7 does. That's why I went with "LiveTile", since it's made to look and behave like a livetile on the start screen. Do you have any good suggestions? I'm fine with renaming it - just out of ideas on that one :)

**Comment by timheuer** [comment]
Definitely low priority though.  I think we'll see this pattern emerge within other apps as well.  Will ask around to see what folks are calling it

**Comment by dotMorten** [comment]
Considering that changing the name of the control is a breaking change, we should probably figure the name out before making the project public though.
I used to call the control "SlideView". It slides items across one at a time. ItemsSlider? LiveItemsSlider? Banana?
