### ISSUE TITLE
Backbutton does not work for all scenarios.

### ISSUE THREAD

**Issue by jnystrom** [timheuer/callisto#47]
When there are multiple levels of flyouts, the backbutton does not seem to work as expected.  The backbutton only seems to go back to the settings charm.  If I have gone from one flyout to another flyout, the backbutton should move me to the previous flyout, at least this is my expectation.

**Comment by timheuer** [comment]
Would you want an event handler solution do you think?  The fix I'm leaning toward right now is to assume a navigation stack/frame parent and call GoBack, or if none, then trigger SettingsPane.Show again.

**Comment by jnystrom** [comment]
so right now I took your codebase and created a backbutton delegate.  Do you have a frame and ability to use navigation frame in the current code?  Right now what I do is call show() on each flyout and actually handle how the flyout is closed myself (backbutton, manual, or light dismiss).  The light dismiss also is not currently handled with multiple flyouts as only the top one is closed if user clicks off the flyout.  If you could handle these scenarios with its own navigation frame, that would be helpful and save me a lot of code.

**Comment by jnystrom** [comment]
Hey Tim, if you want help with this issue and have an plan, let me know and I can try to help out.

**Comment by timheuer** [comment]
My initial gut tells me to look for a Command used, and if none, assume the
default of showing the SettingsPane again.

---

http://timheuer.com/blog/
twitter: @timheuer

On Fri, Aug 3, 2012 at 7:44 AM, jnystrom <
reply@reply.github.com

**Comment by jnystrom** [comment]
do you not want to handle the possibility of multiple flyouts?  Do you want the client to continue to deal with that themselves?  I have run into issues with having to manually manage multiple flyouts and dealing with the backbutton vs. light dismiss vs manual close.  Let me know what your vision is.  Thanks.

**Comment by jeffklawiter** [comment]
I'm curious if they solution could be to offer a second SettingsFlyout control, one that has the content set as a frame and exposes navigation events and methods. The problem then lies in if the navigated controls want to expose data in the flyout header. Though this could be accomplished by checking to see if they implement an interface or an attribute that expose such information. 

I've made a fork that I'm going to play around doing such a thing. Right now my idea is only half implemented and may not pan out.

**Comment by jeffklawiter** [comment]
So I was able to get an example working. https://github.com/jeffklawiter/callisto
. 
Since SettingsFlyout is currently sealed I had to go the route of making a base class and having SettingsFlyout and the new SettingsFlyoutFrame inherit from this. What isn't ideal about this approach is now there needs to be two templates with no apparent need to the user. Now the two could be merged into one but it may present a confusing interface since if someone uses the control to allow navigable content they can't set the Content property

I updated the AppSettings class to have AddNavigationCommand that will handle setting up the SettingsFlyoutFrame.

I did make one breaking change. Since going with two controls and a base class the SettingsFlyoutWidth enum really needed to be in the namespace and not encapsulated by the base class. 

So overall I'm not sure I'm happy with the approach. I need to mull it over and see if I can come up with something more elegant that still doesn't break. Maybe make SettingsFlyout generic and if the Type passed into it inherits from Page have it switch to make the content into a Frame.

I'm curious what others think.
