### ISSUE TITLE
MenuItem needs to have Header property

### ISSUE THREAD

**Issue by stefanolson** [timheuer/callisto#95]
I am using menuitem in the same way that I do in WPF to display a stack panel containing a couple of text blocks.  Unfortunately menuitem as it currently stands only has a Text property, not a content or header property.  The problem here is avoiding breaking any existing code, but I wonder if a Header property should be added and only displayed if non-null?

**Comment by timheuer** [comment]
What would this look like?  There is no modern UI that has this in menu

-th

**Comment by stefanolson** [comment]
WPF has a Header property.  The telerik context menu for windows phone has a content property.  Here's what it looks like in WPF.  Looks exactly the same in windows phone. I have modified menu item as discussed above and that is displayed at the bottom of this picture (admittedly, I have no idea why the pop-up has been placed so far below the item that is supposed to be related to, but I will take a look at that soon):
https://skydrive.live.com/redir?resid=E862238D79090552!332&authkey=!ANM7KDwBfxVDYT4

Stefan

**Comment by timheuer** [comment]
I've reviewed all the guidelines and for Menu there is no affordance for this UI.  My goal with this project is to stick with the guidelines in the even that when/if the real controls come online it will be an easy transition.  Given this I'm going to decline this modification.  

A tooltip would be preferred here for the helper information and can be achieved by setting it on MenuItem

**Comment by stefanolson** [comment]
Tim,

The behaviour that I am attempting to have is entirely consistent with Microsoft's other Metro (or whatever it's called these days) based platform, windows phone.  The windows phone MenuItem is derived from the System.Windows.Controls.HeaderedItemsControl class, where header is an object I have multiple menus in my application where the user needs to select something so I display it visually, or with more information so they know what they are selecting 

For me as a developer this is one of the major frustrations of WinRt and windows phone. WPF is an outstanding, almost perfect platform and it's been redeveloped twice first as Silverlight and then WinRt but so many of the brilliant pieces of functionality and design in WPF have not been pulled across. WPF gave immense flexibility, which made working with it a largely a joy. What I'm trying to do here in this particular case it make the application more usable and intuitive for the end user so they understand what they are going to be selecting and yet according to what you are suggesting, the platform is not supporting that. Very weird.

A tooltip would not help in this particular situation because the user needs to select one of the two options.

Anyway, I will just grab the existing code and add it into my code.

...Stefan

**Comment by timheuer** [comment]
Hi Stefan,

I don't disagree and empathize with the frustration you have of "thinks that worked in <fill-in-the-blank> XAML version."  You note that WPF gave you the flexibility...XAML still does that.  What I'm saying is that this request conflicts with the goals of this project in certain areas.  Namely the prescribed experiences around this particular area has some clear guidelines I'm trying to match.  I do this in order to ensure the best chance of expectation setting in the event that the WinRT platform actually provides these controls in-box.  I'd set a goal early on to conform as best I could to the guidelines to ensure this principle and that apps would be great on Windows and feel like the OS itself.

Stating that WPF or Phone has this particular feature doesn't mean it is suddenly default in the implementation of design principles that Windows wants.  Take a look at the various Menus in the OS...you will not see the experience you are desiring: http://sdrv.ms/PdVmfo.

Tooltip doesn't require the user to **select** the item, they can hover over the menu and it will show.
